networks:
  todo-network:
    driver: bridge

services:
  # ASP.NET Core API
  todo-api:
    build:
      context: ./TodoApi
      dockerfile: Dockerfile
    container_name: todo-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5000:80"
    networks:
      - todo-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/api/todo"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # React Frontend
  todo-frontend:
    build:
      context: ./todo-frontend
      dockerfile: Dockerfile
    container_name: todo-frontend
    ports:
      - "3000:80"
    networks:
      - todo-network
    depends_on:
      todo-api:
        condition: service_healthy
    environment:
      - NODE_ENV=production