version: '3.8'

networks:
  todo-network:
    driver: bridge

services:
  # ASP.NET Core API (Development)
  todo-api:
    build:
      context: ./TodoApi
      dockerfile: Dockerfile
    container_name: todo-api-dev
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5000:80"
    networks:
      - todo-network
    volumes:
      - ./TodoApi:/app/src
    command: ["dotnet", "watch", "run", "--project", "/app/src"]

  # React Frontend (Development with hot reload)
  todo-frontend-dev:
    image: node:18.18.0-alpine
    container_name: todo-frontend-dev
    working_dir: /app
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    networks:
      - todo-network
    volumes:
      - ./todo-frontend:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    depends_on:
      - todo-api